// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	ProtoMessage
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type ProtoMessage_DataType int32

const (
	ProtoMessage_Binary ProtoMessage_DataType = 0
	ProtoMessage_BSON   ProtoMessage_DataType = 1
)

var ProtoMessage_DataType_name = map[int32]string{
	0: "Binary",
	1: "BSON",
}
var ProtoMessage_DataType_value = map[string]int32{
	"Binary": 0,
	"BSON":   1,
}

func (x ProtoMessage_DataType) Enum() *ProtoMessage_DataType {
	p := new(ProtoMessage_DataType)
	*p = x
	return p
}
func (x ProtoMessage_DataType) String() string {
	return proto.EnumName(ProtoMessage_DataType_name, int32(x))
}
func (x *ProtoMessage_DataType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProtoMessage_DataType_value, data, "ProtoMessage_DataType")
	if err != nil {
		return err
	}
	*x = ProtoMessage_DataType(value)
	return nil
}
func (ProtoMessage_DataType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type ProtoMessage struct {
	Type             *string                `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	Queue            *string                `protobuf:"bytes,2,req,name=queue" json:"queue,omitempty"`
	Sender           *string                `protobuf:"bytes,3,req,name=sender" json:"sender,omitempty"`
	Topic            *string                `protobuf:"bytes,4,req,name=topic" json:"topic,omitempty"`
	Seq              *int64                 `protobuf:"varint,5,req,name=seq" json:"seq,omitempty"`
	Starttime        []byte                 `protobuf:"bytes,6,req,name=starttime" json:"starttime,omitempty"`
	Endtime          []byte                 `protobuf:"bytes,7,req,name=endtime" json:"endtime,omitempty"`
	DataType         *ProtoMessage_DataType `protobuf:"varint,8,req,name=dataType,enum=main.ProtoMessage_DataType" json:"dataType,omitempty"`
	Data             []byte                 `protobuf:"bytes,9,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *ProtoMessage) Reset()                    { *m = ProtoMessage{} }
func (m *ProtoMessage) String() string            { return proto.CompactTextString(m) }
func (*ProtoMessage) ProtoMessage()               {}
func (*ProtoMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProtoMessage) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *ProtoMessage) GetQueue() string {
	if m != nil && m.Queue != nil {
		return *m.Queue
	}
	return ""
}

func (m *ProtoMessage) GetSender() string {
	if m != nil && m.Sender != nil {
		return *m.Sender
	}
	return ""
}

func (m *ProtoMessage) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

func (m *ProtoMessage) GetSeq() int64 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

func (m *ProtoMessage) GetStarttime() []byte {
	if m != nil {
		return m.Starttime
	}
	return nil
}

func (m *ProtoMessage) GetEndtime() []byte {
	if m != nil {
		return m.Endtime
	}
	return nil
}

func (m *ProtoMessage) GetDataType() ProtoMessage_DataType {
	if m != nil && m.DataType != nil {
		return *m.DataType
	}
	return ProtoMessage_Binary
}

func (m *ProtoMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ProtoMessage)(nil), "main.ProtoMessage")
	proto.RegisterEnum("main.ProtoMessage_DataType", ProtoMessage_DataType_name, ProtoMessage_DataType_value)
}

var fileDescriptor0 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x8e, 0x3b, 0x6e, 0x84, 0x30,
	0x14, 0x45, 0x03, 0x18, 0x30, 0x2f, 0x40, 0x88, 0x2b, 0x4b, 0x69, 0x10, 0x55, 0x9a, 0xb8, 0xc8,
	0x12, 0x50, 0xda, 0x7c, 0xa4, 0x64, 0x03, 0x56, 0x78, 0x1a, 0xb9, 0xe0, 0x67, 0x9b, 0x82, 0xad,
	0xce, 0x6a, 0xc6, 0xf6, 0x7c, 0x34, 0xe5, 0x39, 0xf7, 0x5d, 0xbd, 0x0b, 0xd5, 0x88, 0xc6, 0xc8,
	0x03, 0x8a, 0x45, 0xcf, 0x76, 0x66, 0x64, 0x94, 0x6a, 0xea, 0x8e, 0x11, 0x94, 0x3f, 0x9e, 0x3f,
	0xcf, 0x21, 0x2b, 0x81, 0xd8, 0x7d, 0x41, 0x1e, 0xb5, 0xf1, 0x6b, 0xc1, 0x2a, 0x48, 0xd7, 0x0d,
	0x37, 0xe4, 0x71, 0xc0, 0x1a, 0x32, 0x83, 0xd3, 0x80, 0x9a, 0x27, 0xd7, 0xd8, 0xce, 0x8b, 0xfa,
	0xe7, 0x24, 0xe0, 0x23, 0x24, 0x06, 0x57, 0x9e, 0x3a, 0x48, 0xd8, 0x33, 0x14, 0xc6, 0x4a, 0x6d,
	0xad, 0x1a, 0x91, 0x67, 0x4e, 0x95, 0xec, 0x09, 0x72, 0xd7, 0x0e, 0x22, 0x0f, 0xe2, 0x0d, 0xe8,
	0x20, 0xad, 0xfc, 0xf3, 0x0f, 0xa9, 0x33, 0xf5, 0xfb, 0x8b, 0xf0, 0xb3, 0xc4, 0xfd, 0x24, 0xf1,
	0x71, 0x39, 0xf1, 0xdb, 0xfc, 0x39, 0x2f, 0x7c, 0xb9, 0x6b, 0x81, 0xde, 0x12, 0x80, 0xac, 0x57,
	0x93, 0xd4, 0x7b, 0xf3, 0xc0, 0x28, 0x90, 0xfe, 0xf7, 0xfb, 0xab, 0x89, 0x4e, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xc0, 0xcb, 0xf7, 0xdf, 0xf2, 0x00, 0x00, 0x00,
}
